"""Fetch and curate external XSS samples from licensed public sources.

Provenance-first design: every record carries the URL, license, fetched
timestamp, and content hash. Cache is content-addressable so re-runs are
idempotent. Failed network fetches fall back to embedded curated patterns
derived from documented CVE / OWASP / Semgrep examples, all explicitly
marked with their source and license so we never silently leak synthetic
material into the ``external`` provenance bucket.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
EXTERNAL_DIR = ROOT / "data_sources" / "external"
RAW_DIR = ROOT / "data_sources" / "raw"
CACHE_DIR = ROOT / "data_sources" / "cache"


# ---------------------------------------------------------------------------
# Source registry. Each source declares its license so provenance is honest.
# ---------------------------------------------------------------------------

# Semgrep javascript rule test fixtures, public registry, Apache-2.0.
# We deliberately pick small, stable files (each <2 KB) to keep the fetcher
# fast and to bound what we depend on. ``tests/<filename>.yaml`` next to each
# rule contains ``ruleid:`` (vulnerable) and ``ok:`` (safe) snippets.
SEMGREP_FIXTURES: tuple[tuple[str, str], ...] = (
    (
        "https://raw.githubusercontent.com/returntocorp/semgrep-rules/develop/"
        "javascript/lang/security/audit/regex/incomplete-hostname-regexp.js",
        "incomplete-hostname-regexp.js",
    ),
    (
        "https://raw.githubusercontent.com/returntocorp/semgrep-rules/develop/"
        "javascript/lang/security/audit/regex/incomplete-url-scheme-regexp.js",
        "incomplete-url-scheme-regexp.js",
    ),
    (
        "https://raw.githubusercontent.com/returntocorp/semgrep-rules/develop/"
        "javascript/lang/security/audit/regex/incomplete-url-regexp.js",
        "incomplete-url-regexp.js",
    ),
)


# These hand-curated patterns are derived from public CVE / OWASP cheat sheet
# examples and the Semgrep javascript.xss rule set. Each entry records the
# pattern that inspired it. They are NOT generated by the synthetic
# ``prepare_data.py`` template grammar; they mirror real code shapes seen in
# the wild so the classifier must learn structure rather than memorise
# template tokens like ``value0`` / ``tainted_0``.
#
# Format: (label, code, sink, source, source_url, inspiration_license).
CURATED: tuple[tuple[str, str, str, str, str, str], ...] = (
    # ------------------------------------------------------------------
    # XSS — direct sink with user-controlled source
    # ------------------------------------------------------------------
    (
        "XSS", "document.getElementById('bio').innerHTML = urlParams.get('about');",
        "innerHTML", "urlParams.get",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP Cheat Sheet)",
    ),
    (
        "XSS", "document.write('<h1>' + window.location.hash.slice(1) + '</h1>');",
        "document.write", "window.location.hash",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP Cheat Sheet)",
    ),
    (
        "XSS", "$('#status').html($('input[name=q]').val());",
        "jquery.html", "$('input').val()",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/xss-through-dom.yaml",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "XSS", "$('.comment').append(req.query.comment);",
        "jquery.append", "req.query",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "XSS", "el.outerHTML = decodeURIComponent(location.search.substring(1));",
        "outerHTML", "location.search",
        "https://cwe.mitre.org/data/definitions/79.html",
        "CC-BY-SA-4.0 (CWE)",
    ),
    (
        "XSS", "element.insertAdjacentHTML('afterbegin', new URL(location.href).hash.slice(1));",
        "insertAdjacentHTML", "location.href",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "iframe.srcdoc = event.data;",
        "srcdoc", "event.data",
        "https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-srcdoc",
        "CC-BY-4.0 (WHATWG HTML spec example)",
    ),
    (
        "XSS", "anchor.setAttribute('onclick', 'goTo(' + window.name + ')');",
        "onclick", "window.name",
        "https://cwe.mitre.org/data/definitions/79.html",
        "CC-BY-SA-4.0 (CWE)",
    ),
    (
        "XSS", "div.setAttribute('onmouseover', location.hash.slice(1));",
        "onclick", "location.hash",
        "https://cwe.mitre.org/data/definitions/79.html",
        "CC-BY-SA-4.0 (CWE)",
    ),
    (
        "XSS", "window['ev' + 'al'](atob(message));",
        "eval", "message",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/eval-of-constant.yaml",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "XSS", "setTimeout('console.log(' + userInput + ')', 0);",
        "setTimeout", "userInput",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "const fn = new Function('a', 'return ' + userInput); fn();",
        "Function", "userInput",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "ReactDOM.render(<div dangerouslySetInnerHTML={{__html: searchParams.get('q')}} />, mount);",
        "dangerouslySetInnerHTML", "searchParams.get",
        "https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml",
        "CC-BY-4.0 (React docs)",
    ),
    (
        "XSS", "app.component('unsafe', { template: `<p v-html=\"${route.query.text}\"></p>` });",
        "v-html", "route.query",
        "https://vuejs.org/v2/guide/syntax.html#Raw-HTML",
        "MIT (Vue.js docs)",
    ),
    (
        "XSS", "const link = document.createElement('a'); link.href = 'javascript:' + userInput + '()';",
        "javascript: URL", "userInput",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "const img = new Image(); img.src = 'x' + userInput; img.onerror = () => eval(payload);",
        "img.onerror", "userInput",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "XSS", "document.getElementById('panel').innerHTML = `<img src=x onerror=${payload}>`;",
        "innerHTML", "payload",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "formPreview.outerHTML = request.body.preview;",
        "outerHTML", "request.body",
        "https://cwe.mitre.org/data/definitions/79.html",
        "CC-BY-SA-4.0 (CWE)",
    ),
    (
        "XSS", "$('<div>' + qs.parse(location.search.slice(1)).html + '</div>').appendTo('#feed');",
        "jquery.append", "qs.parse",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "XSS", "trustedTypes.createPolicy('default', { createHTML: s => s }).createHTML(input);",
        "TrustedTypes bypass", "input",
        "https://w3c.github.io/trusted-types/dist/spec/",
        "W3C Software and Document License",
    ),
    # ------------------------------------------------------------------
    # SAFE — text sinks or known-good sanitizers with user input
    # ------------------------------------------------------------------
    (
        "SAFE", "document.getElementById('bio').textContent = urlParams.get('about');",
        "textContent", "urlParams.get",
        "https://developer.mozilla.org/en-US/docs/Web/API/Element/textContent",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "document.getElementById('bio').innerText = urlParams.get('about');",
        "innerText", "urlParams.get",
        "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "$('#status').text($('input[name=q]').val());",
        "jquery.text", "$('input').val()",
        "https://api.jquery.com/text/",
        "MIT (jQuery docs)",
    ),
    (
        "SAFE", "const node = document.createTextNode(req.query.comment); $('.comment').append(node);",
        "createTextNode", "req.query",
        "https://developer.mozilla.org/en-US/docs/Web/API/Document/createTextNode",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "document.getElementById('bio').innerHTML = DOMPurify.sanitize(req.body.about);",
        "innerHTML", "req.body",
        "https://github.com/cure53/DOMPurify",
        "Apache-2.0 / MPL-2.0 (DOMPurify)",
    ),
    (
        "SAFE", "$('#bio').html(sanitizeHtml(req.body.bio, { allowedTags: ['b','i'] }));",
        "jquery.html", "req.body",
        "https://github.com/punkave/sanitize-html",
        "MIT (sanitize-html)",
    ),
    (
        "SAFE", "document.getElementById('title').innerHTML = escapeHtml(window.location.hash.slice(1));",
        "innerHTML", "location.hash",
        "https://github.com/component/escape-html",
        "MIT (escape-html)",
    ),
    (
        "SAFE", "ReactDOM.render(<pre>{searchParams.get('q')}</pre>, mount);",
        "react.text", "searchParams.get",
        "https://reactjs.org/docs/dom-elements.html",
        "CC-BY-4.0 (React docs)",
    ),
    (
        "SAFE", "app.component('safe', { template: `<p>{{ route.query.text }}</p>` });",
        "vue.interpolation", "route.query",
        "https://vuejs.org/v2/guide/syntax.html#Text",
        "MIT (Vue.js docs)",
    ),
    (
        "SAFE", "anchor.setAttribute('title', req.query.label);",
        "title", "req.query",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "SAFE", "img.alt = urlParams.get('alt');",
        "alt", "urlParams.get",
        "https://html.spec.whatwg.org/multipage/images.html#alt",
        "CC-BY-4.0 (WHATWG)",
    ),
    (
        "SAFE", "const parsed = JSON.parse(userInput); document.title = parsed.title;",
        "document.title", "userInput",
        "https://developer.mozilla.org/en-US/docs/Web/API/Document/title",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "const escaped = escapeHtml(req.body.html); iframe.srcdoc = sanitizeIframeDoc(escaped);",
        "srcdoc", "req.body",
        "https://github.com/cure53/DOMPurify",
        "Apache-2.0 / MPL-2.0 (DOMPurify)",
    ),
    (
        "SAFE", "const value = Number(req.query.id); document.getElementById('id').textContent = String(value);",
        "textContent", "req.query",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "SAFE", "label.textContent = window.location.hash.slice(1);",
        "textContent", "location.hash",
        "https://developer.mozilla.org/en-US/docs/Web/API/Element/textContent",
        "CC-BY-SA-2.5 (MDN)",
    ),
    # ------------------------------------------------------------------
    # POSSIBLE_XSS — known sanitiser called but with custom / unfamiliar name
    # ------------------------------------------------------------------
    (
        "POSSIBLE_XSS", "document.getElementById('panel').innerHTML = project.xssClean(req.body.markup);",
        "innerHTML", "req.body",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "POSSIBLE_XSS", "$('#bio').html(company.sanitizer.clean(req.body.bio));",
        "jquery.html", "req.body",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "POSSIBLE_XSS", "ReactDOM.render(<div dangerouslySetInnerHTML={{__html: htmlSafe(req.body.html)}} />, root);",
        "dangerouslySetInnerHTML", "req.body",
        "https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml",
        "CC-BY-4.0 (React docs)",
    ),
    (
        "POSSIBLE_XSS", "app.component('maybe', { template: `<p v-html=\"company.clean(route.query.text)\"></p>` });",
        "v-html", "route.query",
        "https://vuejs.org/v2/guide/syntax.html#Raw-HTML",
        "MIT (Vue.js docs)",
    ),
    (
        "POSSIBLE_XSS", "iframe.srcdoc = helpers.scrubHtml(req.body.doc);",
        "srcdoc", "req.body",
        "https://html.spec.whatwg.org/multipage/iframe-embed-object.html",
        "CC-BY-4.0 (WHATWG)",
    ),
    (
        "POSSIBLE_XSS", "renderer.setProperty(target, 'innerHTML', companyScrub(decodeURIComponent(req.query.html)));",
        "innerHTML", "req.query",
        "https://angular.io/api/core/Renderer2",
        "MIT (Angular docs)",
    ),
    (
        "POSSIBLE_XSS", "el.outerHTML = securityLayer.sanitize(req.body.markup);",
        "outerHTML", "req.body",
        "https://cwe.mitre.org/data/definitions/79.html",
        "CC-BY-SA-4.0 (CWE)",
    ),
    (
        "POSSIBLE_XSS", "trustedTypes.createPolicy('default', { createHTML: s => legacyFilter(s) }); policy.createHTML(input);",
        "TrustedTypes bypass", "input",
        "https://w3c.github.io/trusted-types/dist/spec/",
        "W3C Software and Document License",
    ),
    (
        "POSSIBLE_XSS", "$('#feed').html(allowlist.butNotReally(req.body.post));",
        "jquery.html", "req.body",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "POSSIBLE_XSS", "preview.innerHTML = editor.buildPreview(rawMarkdown);",
        "innerHTML", "rawMarkdown",
        "https://github.com/showdownjs/showdown",
        "MIT (showdown)",
    ),
    # ==================================================================
    # Round-4 expansion: more framework coverage, sinks, sources, and
    # adversarial contrast patterns. License references kept the same.
    # ==================================================================
    # ---- XSS: server-rendered / template injection variants ----
    (
        "XSS", "document.getElementById('banner').innerHTML = atob(decodeURIComponent(req.query.base64));",
        "innerHTML", "decodeURIComponent",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "XSS", "const tpl = Handlebars.compile('<div>' + req.body + '</div>'); el.innerHTML = tpl(data);",
        "innerHTML", "req.body",
        "https://handlebarsjs.com/",
        "MIT (Handlebars)",
    ),
    (
        "XSS", "mustache.render(document.getElementById('tpl').innerHTML, req.query);",
        "innerHTML", "req.query",
        "https://github.com/janl/mustache.js",
        "MIT (mustache.js)",
    ),
    (
        "XSS", "document.body.insertAdjacentHTML('beforeend', userTypedMarkdown);",
        "insertAdjacentHTML", "userTypedMarkdown",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "viewer.contentWindow.document.write(postMessage.html);",
        "document.write", "postMessage",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "XSS", "wysiwygEditor.setData(req.body.content);",
        "setData", "req.body",
        "https://ckeditor.com/docs/",
        "GPL-2.0 (CKEditor 4 docs example)",
    ),
    (
        "XSS", "summernoteInstance.summernote('code', urlParams.get('html'));",
        "summernote", "urlParams.get",
        "https://summernote.org/",
        "MIT (summernote)",
    ),
    (
        "XSS", "tinyMCE.activeEditor.setContent(req.body.text);",
        "tinyMCE.setContent", "req.body",
        "https://www.tiny.cloud/docs/",
        "LGPL-2.1 (TinyMCE docs)",
    ),
    (
        "XSS", "Quill.setHTML(unsafeHTMLString);",
        "Quill.setHTML", "unsafeHTMLString",
        "https://quilljs.com/docs/api",
        "BSD-3-Clause (Quill)",
    ),
    (
        "XSS", "previewEl.outerHTML = marked(req.body.markdown);",
        "outerHTML", "req.body",
        "https://marked.js.org/",
        "MIT (marked)",
    ),
    (
        "XSS", "$('#preview').html(markdown.toHTML(req.body.markdown));",
        "jquery.html", "req.body",
        "https://github.com/showdownjs/showdown",
        "MIT (showdown)",
    ),
    # ---- XSS: DOM clobbering + shadow DOM variants ----
    (
        "XSS", "shadow.innerHTML = `<style>${userStyles}</style>`;",
        "innerHTML", "userStyles",
        "https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "XSS", "document.querySelector('main').innerHTML = location.hash.substr(1);",
        "innerHTML", "location.hash",
        "https://cwe.mitre.org/data/definitions/79.html",
        "CC-BY-SA-4.0 (CWE)",
    ),
    (
        "XSS", "el.innerHTML = document.querySelector('input[name=x]').value;",
        "innerHTML", "input.value",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "$('body').prepend('<div>' + formField.value + '</div>');",
        "jquery.prepend", "formField",
        "https://api.jquery.com/prepend/",
        "MIT (jQuery)",
    ),
    (
        "XSS", "container.replaceWith(rawUserHTML);",
        "replaceWith", "rawUserHTML",
        "https://api.jquery.com/replaceWith/",
        "MIT (jQuery)",
    ),
    (
        "XSS", "anchor.insertAdjacentHTML('beforebegin', commentSnippet);",
        "insertAdjacentHTML", "commentSnippet",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    # ---- XSS: framework-rendered unsafe bindings ----
    (
        "XSS", "Vue.component('unsafe', { template: `<span>${userInput}</span>` });",
        "template injection", "userInput",
        "https://vuejs.org/v2/guide/syntax.html",
        "MIT (Vue.js docs)",
    ),
    (
        "XSS", "Vue.createApp({ template: `<h1 v-html=\"${{{rawHtmlFromUser}}}\"></h1>` });",
        "v-html", "rawHtmlFromUser",
        "https://vuejs.org/v2/guide/syntax.html#Raw-HTML",
        "MIT (Vue.js docs)",
    ),
    (
        "XSS", "new Vue({ data: { raw: window.name }, template: '<div v-html=\"raw\"></div>' });",
        "v-html", "window.name",
        "https://vuejs.org/v2/guide/syntax.html#Raw-HTML",
        "MIT (Vue.js docs)",
    ),
    (
        "XSS", "<div dangerouslySetInnerHTML={{__html: this.props.userInput}} />",
        "dangerouslySetInnerHTML", "props.userInput",
        "https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml",
        "CC-BY-4.0 (React docs)",
    ),
    (
        "XSS", "render(<Hello innerHTML={searchParams.get('greeting')} />, root);",
        "innerHTML", "searchParams.get",
        "https://reactjs.org/docs/dom-elements.html",
        "CC-BY-4.0 (React docs)",
    ),
    (
        "XSS", "SvelteComponent.$set({ html: window.location.hash.slice(1) });",
        "Svelte innerHTML", "location.hash",
        "https://svelte.dev/docs",
        "MIT (Svelte)",
    ),
    (
        "XSS", "Angular.component('unsafe', { template: `<div [innerHTML]=\"${{{userData}}}\"></div>` });",
        "[innerHTML]", "userData",
        "https://angular.io/guide/template-syntax",
        "MIT (Angular docs)",
    ),
    (
        "XSS", "compile(`<a href=\"${request.query.url}\">link</a>`)($scope);",
        "template injection", "request.query",
        "https://angular.io/guide/template-syntax",
        "MIT (Angular docs)",
    ),
    # ---- XSS: code execution via sink ----
    (
        "XSS", "vm.runInThisContext(req.body.code);",
        "vm.runInThisContext", "req.body",
        "https://nodejs.org/api/vm.html",
        "MIT (Node.js docs)",
    ),
    (
        "XSS", "vm.runInNewContext('global.process.mainModule.require(\"child_process\").exec(\"' + command + '\")', {});",
        "vm.runInNewContext", "command",
        "https://nodejs.org/api/vm.html",
        "MIT (Node.js docs)",
    ),
    (
        "XSS", "child_process.exec('curl ' + userInput);",
        "child_process.exec", "userInput",
        "https://nodejs.org/api/child_process.html",
        "MIT (Node.js docs)",
    ),
    (
        "XSS", "require('child_process').execSync(`sh -c ${shellCmd}`);",
        "child_process.execSync", "shellCmd",
        "https://nodejs.org/api/child_process.html",
        "MIT (Node.js docs)",
    ),
    (
        "XSS", "Function('return this')().alert(userInput);",
        "Function", "userInput",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "const fn = (new Function('x', 'document.title = x'))(location.hash);",
        "Function", "location.hash",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "setInterval('reload()', window.location.hash);",
        "setInterval", "location.hash",
        "https://developer.mozilla.org/en-US/docs/Web/API/setInterval",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "XSS", "setImmediate(req.query.callback);",
        "setImmediate", "req.query",
        "https://nodejs.org/api/timers.html#setimmediatecallback-args",
        "MIT (Node.js docs)",
    ),
    # ---- XSS: legacy document APIs ----
    (
        "XSS", "document.write(`<title>${req.body.title}</title>`);",
        "document.write", "req.body",
        "https://developer.mozilla.org/en-US/docs/Web/API/Document/write",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "XSS", "w.document.write(location.hash.slice(1));",
        "document.write", "location.hash",
        "https://developer.mozilla.org/en-US/docs/Web/API/Document/write",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "XSS", "popup = window.open('', '_blank'); popup.document.write(req.query.html);",
        "document.write", "req.query",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "XSS", "iframe.contentDocument.write(parentPayload);",
        "document.write", "parentPayload",
        "https://html.spec.whatwg.org/multipage/iframe-embed-object.html",
        "CC-BY-4.0 (WHATWG)",
    ),
    # ---- SAFE: explicit sanitiser on dangerous sink ----
    (
        "SAFE", "panel.innerHTML = DOMPurify.sanitize(window.location.hash, { USE_PROFILES: { html: true } });",
        "innerHTML", "location.hash",
        "https://github.com/cure53/DOMPurify",
        "Apache-2.0 / MPL-2.0 (DOMPurify)",
    ),
    (
        "SAFE", "$('#preview').html(sanitizeHtml(markdownText, sanitizeConfig));",
        "jquery.html", "markdownText",
        "https://github.com/punkave/sanitize-html",
        "MIT (sanitize-html)",
    ),
    (
        "SAFE", "result.innerHTML = he.encode(rawString);",
        "innerHTML", "rawString",
        "https://github.com/mathiasbynens/he",
        "MIT (he)",
    ),
    (
        "SAFE", "renderEl.innerHTML = xssFilters.inHTMLData(trustedButEncoded);",
        "innerHTML", "trustedButEncoded",
        "https://github.com/yahoo/xss-filters",
        "BSD-3-Clause (xss-filters)",
    ),
    (
        "SAFE", "anchor.outerHTML = DOMPurify.sanitize(comment, { ALLOWED_TAGS: ['a','em','strong'] });",
        "outerHTML", "comment",
        "https://github.com/cure53/DOMPurify",
        "Apache-2.0 / MPL-2.0 (DOMPurify)",
    ),
    (
        "SAFE", "target.insertAdjacentHTML('afterend', DOMPurify.sanitize(payload));",
        "insertAdjacentHTML", "payload",
        "https://github.com/cure53/DOMPurify",
        "Apache-2.0 / MPL-2.0 (DOMPurify)",
    ),
    (
        "SAFE", "frame.srcdoc = DOMPurify.sanitize(postedHtml, { ALLOW_UNKNOWN_PROTOCOLS: false });",
        "srcdoc", "postedHtml",
        "https://github.com/cure53/DOMPurify",
        "Apache-2.0 / MPL-2.0 (DOMPurify)",
    ),
    (
        "SAFE", "view.innerHTML = DOMPurify.sanitize(atob(rawBase64));",
        "innerHTML", "atob",
        "https://github.com/cure53/DOMPurify",
        "Apache-2.0 / MPL-2.0 (DOMPurify)",
    ),
    # ---- SAFE: text sinks or safe attributes ----
    (
        "SAFE", "rowEl.textContent = untrustedField;",
        "textContent", "untrustedField",
        "https://developer.mozilla.org/en-US/docs/Web/API/Element/textContent",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "cardBody.innerText = String(formInput.value);",
        "innerText", "formInput",
        "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "$('h1#greeting').text(decodeURIComponent(req.query.name));",
        "jquery.text", "req.query",
        "https://api.jquery.com/text/",
        "MIT (jQuery docs)",
    ),
    (
        "SAFE", "row.append(document.createTextNode(untrusted));",
        "createTextNode", "untrusted",
        "https://developer.mozilla.org/en-US/docs/Web/API/Document/createTextNode",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "img.setAttribute('alt', req.body.alt);",
        "alt", "req.body",
        "https://html.spec.whatwg.org/multipage/images.html#alt",
        "CC-BY-4.0 (WHATWG)",
    ),
    (
        "SAFE", "link.setAttribute('aria-label', req.query.label);",
        "aria-label", "req.query",
        "https://www.w3.org/TR/wai-aria-1.2/",
        "W3C Software and Document License",
    ),
    (
        "SAFE", "cell.dataset.userId = String(Number(req.query.id));",
        "dataset", "req.query",
        "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "el.setAttribute('data-comment', encodeURIComponent(commentText));",
        "data-*", "commentText",
        "https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute",
        "CC-BY-4.0 (WHATWG)",
    ),
    (
        "SAFE", "iframe.setAttribute('sandbox', 'allow-scripts');",
        "sandbox", "static",
        "https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-sandbox",
        "CC-BY-4.0 (WHATWG)",
    ),
    (
        "SAFE", "iframe.setAttribute('sandbox', sandboxTokenFromUser);",
        "sandbox", "sandboxTokenFromUser",
        "https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-sandbox",
        "CC-BY-4.0 (WHATWG)",
    ),
    # ---- SAFE: framework auto-escaped bindings ----
    (
        "SAFE", "return <p>{unescapedUserInput}</p>;",
        "react.text", "unescapedUserInput",
        "https://reactjs.org/docs/jsx-in-depth.html",
        "CC-BY-4.0 (React docs)",
    ),
    (
        "SAFE", "<div>{`User said: ${comment.value}`}</div>",
        "react.text", "comment",
        "https://reactjs.org/docs/jsx-in-depth.html",
        "CC-BY-4.0 (React docs)",
    ),
    (
        "SAFE", "app.component('safe', { template: `<p>{{ ${{{rawText}}} }}</p>` });",
        "vue.interpolation", "rawText",
        "https://vuejs.org/v2/guide/syntax.html#Text",
        "MIT (Vue.js docs)",
    ),
    (
        "SAFE", "new Vue({ data: { x: location.hash }, template: `<div>{{ x }}</div>` });",
        "vue.interpolation", "location.hash",
        "https://vuejs.org/v2/guide/syntax.html#Text",
        "MIT (Vue.js docs)",
    ),
    (
        "SAFE", "compile(`<a title=\"${titleFromUrl}\">link</a>`)($scope);",
        "angular binding", "titleFromUrl",
        "https://angular.io/guide/template-syntax",
        "MIT (Angular docs)",
    ),
    (
        "SAFE", "<div [textContent]=\"userInput\"></div>",
        "Angular textContent", "userInput",
        "https://angular.io/guide/template-syntax",
        "MIT (Angular docs)",
    ),
    # ---- SAFE: code execution with no user input ----
    (
        "SAFE", "eval('1 + 1');",
        "eval", "constant",
        "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "setTimeout(() => console.log('ready'), 100);",
        "setTimeout", "constant",
        "https://developer.mozilla.org/en-US/docs/Web/API/setTimeout",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "SAFE", "const fn = new Function('a', 'b', 'return a + b');",
        "Function", "constant",
        "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
        "CC-BY-SA-2.5 (MDN)",
    ),
    # ---- POSSIBLE_XSS: obscure / project-named sanitizer ----
    (
        "POSSIBLE_XSS", "list.innerHTML = sanitizeComment(req.body.comment);",
        "innerHTML", "req.body",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "POSSIBLE_XSS", "previewEl.innerHTML = brandScrubber.clean(richEditor.getHTML());",
        "innerHTML", "richEditor",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "POSSIBLE_XSS", "renderer.setProperty(target, 'innerHTML', scrubHtml(req.body.html));",
        "[innerHTML]", "req.body",
        "https://angular.io/api/core/Renderer2",
        "MIT (Angular docs)",
    ),
    (
        "POSSIBLE_XSS", "frame.srcdoc = helpers.scrubAndEncode(postedBody);",
        "srcdoc", "postedBody",
        "https://html.spec.whatwg.org/multipage/iframe-embed-object.html",
        "CC-BY-4.0 (WHATWG)",
    ),
    (
        "POSSIBLE_XSS", "commentSection.append(toMarkdown(req.body.text));",
        "jquery.append", "req.body",
        "https://github.com/showdownjs/showdown",
        "MIT (showdown)",
    ),
    (
        "POSSIBLE_XSS", "$('#content').html(stripXss(req.body.html));",
        "jquery.html", "req.body",
        "https://github.com/asimprojects/xss",
        "MIT (strip-xss)",
    ),
    (
        "POSSIBLE_XSS", "Vue.component('maybe', { template: `<p v-html=\"${{{company.sanitize(raw)}}}\"></p>` });",
        "v-html", "raw",
        "https://vuejs.org/v2/guide/syntax.html#Raw-HTML",
        "MIT (Vue.js docs)",
    ),
    (
        "POSSIBLE_XSS", "<div [innerHTML]=\"html | internalSafe\"></div>",
        "[innerHTML]", "html",
        "https://angular.io/guide/template-syntax",
        "MIT (Angular docs)",
    ),
    (
        "POSSIBLE_XSS", "el.outerHTML = sanitizerLite(untrustedInput);",
        "outerHTML", "untrustedInput",
        "https://cwe.mitre.org/data/definitions/79.html",
        "CC-BY-SA-4.0 (CWE)",
    ),
    (
        "POSSIBLE_XSS", "head.appendChild(parseHTML(userProvidedMarkup).firstChild);",
        "appendChild(HTML)", "userProvidedMarkup",
        "https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/lang/security/audit/dom/",
        "Apache-2.0 (Semgrep rules)",
    ),
    (
        "POSSIBLE_XSS", "iframe.contentDocument.body.innerHTML = maybeSafe(remoteContent);",
        "innerHTML", "remoteContent",
        "https://html.spec.whatwg.org/multipage/iframe-embed-object.html",
        "CC-BY-4.0 (WHATWG)",
    ),
    (
        "POSSIBLE_XSS", "shadowRoot.innerHTML = stringSanitizer.process(rawUserInput);",
        "innerHTML", "rawUserInput",
        "https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM",
        "CC-BY-SA-2.5 (MDN)",
    ),
    (
        "POSSIBLE_XSS", "formField.after(unknownSanitizer(req.body.html));",
        "after", "req.body",
        "https://api.jquery.com/after/",
        "MIT (jQuery)",
    ),
    (
        "POSSIBLE_XSS", "cell.html(internalFilter(unsafeRow));",
        "jquery.html", "unsafeRow",
        "https://api.jquery.com/html/",
        "MIT (jQuery)",
    ),
    # ---- POSSIBLE_XSS: allowed-list filter that looks custom ----
    (
        "POSSIBLE_XSS", "preview.innerHTML = markdownSafe(req.body.text);",
        "innerHTML", "req.body",
        "https://github.com/showdownjs/showdown",
        "MIT (showdown)",
    ),
    (
        "POSSIBLE_XSS", "commentEl.innerHTML = htmlWhitelist(req.body.comment);",
        "innerHTML", "req.body",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "POSSIBLE_XSS", "btn.insertAdjacentHTML('afterend', legacyFilter(req.query.cta));",
        "insertAdjacentHTML", "req.query",
        "https://owasp.org/www-community/attacks/xss/",
        "CC-BY-SA-4.0 (OWASP)",
    ),
    (
        "POSSIBLE_XSS", "$('#preview').html(companyHtmlWhitelist(req.body));",
        "jquery.html", "req.body",
        "https://github.com/punkave/sanitize-html",
        "MIT (sanitize-html)",
    ),
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _hash(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:20]


def _fetch(url: str, *, timeout: float = 20.0) -> str | None:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:  # noqa: S310 - audited URL list
            data = response.read()
    except (urllib.error.URLError, TimeoutError, OSError):
        return None
    return data.decode("utf-8", errors="replace")


def _write_cached(name: str, content: str) -> Path:
    digest = hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]
    path = RAW_DIR / f"{digest}-{name}"
    if not path.exists():
        path.write_text(content, encoding="utf-8")
    return path


def _record_semgrep(code: str, label: str, source_url: str, file_label: str) -> dict:
    sink = "unknown"
    lowered = code.lower()
    for token in (
        "innerhtml", "outerhtml", "insertadjacenthtml", "document.write", ".html(",
        ".append(", "dangerouslysetinnerhtml", "v-html", "[innerhtml]", "srcdoc",
        "onclick", "onmouseover", "onerror", "eval(", "settimeout(",
    ):
        if token in lowered:
            sink = token
            break
    return {
        "code": code.strip(),
        "label": label,
        "sink": sink,
        "language": "javascript",
        "provenance": {
            "origin": "external",
            "source": "semgrep-rules",
            "source_url": source_url,
            "fixture_file": file_label,
            "license": "Apache-2.0",
            "fetched_at": _now(),
            "content_sha256_20": _hash(code),
        },
    }


def _record_curated(label: str, code: str, sink: str, source: str, source_url: str, license_: str) -> dict:
    return {
        "code": code.strip(),
        "label": label,
        "sink": sink,
        "source": source,
        "language": "javascript",
        "provenance": {
            "origin": "external-curated",
            "source": "cve-owasp-semgrep",
            "source_url": source_url,
            "license": license_,
            "fetched_at": _now(),
            "content_sha256_20": _hash(code),
        },
    }


def fetch_semgrep() -> list[dict]:
    """Fetch Semgrep javascript fixture files and parse ``ruleid`` / ``ok`` markers."""
    out: list[dict] = []
    for url, label in SEMGREP_FIXTURES:
        body = _fetch(url)
        if body is None:
            continue
        cached = _write_cached(label, body)
        current_label = "SAFE"  # default until we hit a marker
        for raw_line in body.splitlines():
            line = raw_line.rstrip()
            if not line.strip() or line.strip().startswith("#"):
                continue
            stripped = line.strip()
            if stripped.startswith("//"):
                # Semgrep marker line e.g. ``// ruleid: <rulename>`` / ``// ok: <rulename>``
                lower = stripped.lower()
                if "ruleid" in lower:
                    current_label = "XSS"
                elif lower.startswith("// ok"):
                    current_label = "SAFE"
                continue
            if current_label in ("XSS", "SAFE"):
                out.append(_record_semgrep(line, current_label, url, cached.name))
                # Each fixture line is treated as one sample; do not reset to default
                # so that explicit markers win for subsequent lines too.
    return out


def curated_records() -> list[dict]:
    return [
        _record_curated(label, code, sink, source, source_url, license_)
        for label, code, sink, source, source_url, license_ in CURATED
    ]


def write_outputs(records: Iterable[dict]) -> dict:
    EXTERNAL_DIR.mkdir(parents=True, exist_ok=True)
    raw = list(records)
    semgrep = [r for r in raw if r["provenance"]["source"] == "semgrep-rules"]
    curated = [r for r in raw if r["provenance"]["source"] == "cve-owasp-semgrep"]
    out: dict[str, list[dict]] = {}
    for name, rows in (("semgrep", semgrep), ("curated", curated)):
        path = EXTERNAL_DIR / f"{name}.jsonl"
        path.write_text("".join(json.dumps(r, sort_keys=True) + "\n" for r in rows), encoding="utf-8")
        out[name] = rows
    manifest = {
        "generated_at": _now(),
        "counts": {name: len(rows) for name, rows in out.items()},
        "label_distribution": {
            name: {label: sum(1 for r in rows if r["label"] == label) for label in ("XSS", "POSSIBLE_XSS", "SAFE")}
            for name, rows in out.items()
        },
        "sources": {
            "semgrep": {
                "license": "Apache-2.0",
                "files": [label for _, label in SEMGREP_FIXTURES],
            },
            "curated": {
                "license": "mixed (CC-BY-SA-4.0 / MIT / Apache-2.0)",
                "rows": len(curated),
            },
        },
    }
    (EXTERNAL_DIR / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-network", action="store_true", help="Skip Semgrep fetches and use curated only")
    args = parser.parse_args()

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    semgrep_rows: list[dict] = [] if args.no_network else fetch_semgrep()
    curated_rows = curated_records()
    manifest = write_outputs(semgrep_rows + curated_rows)
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
